### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by davisbra** [swordlordcodingcrew/fennel#1]
I run fenneld in vps server and I use : http://serveradress:8888 in my browser
a login alert appears  and when I add a user in fennelcli and the information that I added to the login part is not working properly.
how can I resolve this problem?

**Comment by LordEidi** [comment]
We just started with the development / port of Fennel for Go, so I haven't really tested with something else than the demo user. Besides, the current code (and build you probably use) is hard coded to using the htpasswd file your config is pointing to. And the CLI is not doing much yet.

To get things running you will need a htpasswd file. You could use this one: https://github.com/swordlordcodingcrew/fennel/blob/master/demouser.htaccess

The user is demo with password demo...

**Comment by LordEidi** [comment]
I just pushed an update where DB based authentication can be enabled (you would need to replace htpasswd with db in your config and add a user via cli or sqlite3). If you have the means to compile and check, please do. I will trigger a compile and release via Travis somewhen later.
