### ISSUE TITLE
How to compile ?

### ISSUE THREAD

**Issue by schmurfy** [swordlordcodingcrew/fennel#2]
I wanted to give your project a try but "Just compile it yourself" is a rather broad statement regarding go xD
Could you provide some pointers ? Also when checking out your repository there is no go files in the vendored folders, do you use a package manager like gdm or pulling out every dependency by hand ?

**Comment by LordEidi** [comment]
Hehe, indeed. Sorry, the dependencies are a bit of a mess. I should clean up somewhen.

Until then, please have a look at the [.travis.yml](https://github.com/swordlordcodingcrew/fennel/blob/master/.travis.yml) line 24 and ff. This list of used libs should be complete and will be updated when a lib changes or a new one is added.

Btw, line 60 and ff contains the info regarding how to compile. The one line compiles the daemon, the other the CLI client (which has not many features yet).

Oh and I am not sure if the server already serves a CalDAV and CardDAV client as expected. I programmed against the tests from the fennel.js project and only recently started to test with real clients.

**Comment by schmurfy** [comment]
Thanks, I will give it a try :)
Would you accept a pull request to fix the depdency management ?
I have been using gdm so far which allows having them defined in one file and easily fetched as well as ensuring the exact version wanted are fetched.

**Comment by LordEidi** [comment]
Absolutely, of course. 

After hours of reading through different tools and strategies, I hit my head while trying to satisfy both: The CLI as well as GoLand. You/we would have to make sure that the dependencies would work with both...

**Comment by schmurfy** [comment]
the dependency management in golang is still in stone age as far as I am concerned but there are options even if they are not great yet. I will try to see if one of those options fits your project.

**Comment by LordEidi** [comment]
Hehe, exactly my thoughts.

I was a fan of gb, but lately I only had problems with it. I was not able to find a tool which I just can run in the root of the github project and then have it work its magic...

I am very much looking forward to this. Thanks for your help!

**Comment by schmurfy** [comment]
Too bad for gd, I just found it and had great hopes for it, what kind of problems did you have with it ?
One thing I also hate is how the basic setup for compiling go projects forces you to use a specific hierarchy, I don't want anyone else but me dictating how I should arrange my local folders...

So far I have been using gdm with some helper scripts, my main project lives wherever I want and it has a deps folder with its dependencies, it works but fetching non git dependencies like  "golang.org/x/crypto/bcrypt" is a not possible...

**Comment by LordEidi** [comment]
I never really followed up on the problem. It just did not work from one version of go to the next.

What you mention regarding the hierarchy is what I find most irritating with go. I have to change an environment var to tell the compiler where to find what. For every project. Work on multiple projects and things get messy. I hoped the vendor folder would help in cleaning up things a bit. But the problem remains with the compilation step and that every tool behaves (and presumes) a different setup and behaviour.

Speaking of compilation. I was positively surprised how simple Travis could be made to compile my project with my own structure...
