### ISSUE TITLE
Better build instructions

### ISSUE THREAD

**Issue by OldhamMade** [swordlordcodingcrew/fennel#4]
Hey. The project seems really interesting and I'd love to see whether it's usable. However, I'm not a Go developer, and the Makefile doesn't seem to build anything. Would be great to get some better build instructions. I'm installing on FreeBSD.

**Comment by LordEidi** [comment]
Hey. It is somewhat useable but needs quite a bit of love to fully support all the standards. Every implementation of CardDAV and CalDAV is different, although there would be a standard for every detail. It is a real pain to write a server from scratch.

Having said that. Have a look at the Travis config. It shows which libraries are needed and what the commands are to build the server as well as the cli tool.

I quickly looked into the travis world and it does not seem to be a thing to build go binaries for FreeBSD. What I could look into though would be to cross compile on Linux for FreeBSD. Sending me hints would speed things up I guess :)

**Comment by LordEidi** [comment]
I merged the PR by @MFAshby. Hope that fixes this problem. Re-open it otherwise.
