### ISSUE TITLE
Android: Davx5

### ISSUE THREAD

**Issue by MFAshby** [swordlordcodingcrew/fennel#6]
[serverlog.txt](https://github.com/swordlordcodingcrew/fennel/files/6919484/serverlog.txt)
[davx5-debug.zip](https://github.com/swordlordcodingcrew/fennel/files/6919477/davx5-debug.zip)

I tried to connect to fennel from Davx5 (android caldav and carddav sync app) and got the attached error.

**Comment by MFAshby** [comment]
https://github.com/tchapi/davis//issues/8

it's the same as this davx5 is fussy about content-type; which I think can be fixed here by changing fenneld/handler/responder.go SendETreeDocument to call SetStandardXMLHeader instead of SetStandardHTMLHeader.

**Comment by LordEidi** [comment]
Did I get that right? Your last PR contained a change regarding that? Did it work for you?

**Comment by MFAshby** [comment]
Yep, this particular problem was fixed by that PR, thanks for checking and merging!
I'll possibly raise more issues (& PRs if I can) related to using dav5x as I find them.
